# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



$mainMod = Alt
$terminal = kitty
$fileManager = thunar
$menu = wofi

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, F, exec, firefox
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu --show drun
bind = ALT_CTRL, right, workspace, +1
bind = ALT_CTRL, left, workspace, -1
bind = $mainMod, mouse:274, movewindow
bind = , Print, exec, flameshot gui

exec-once = swaybg --image /home/mystic/.config/hypr/wallpaper.png
exec-once = waybar

# Window Decorations! Shadow, Blur, etc.
decoration {
    # 8px same as taskbar, change if wanted.
    rounding = 12

    # I want transparancy to not change, since we have the colored border.
    active_opacity = 1.0
    inactive_opacity = 1

    # Window Shadow
    shadow:enabled = true
    shadow:range = 16
    shadow:render_power = 5
    shadow:color = rgba(0,0,0,0.35)

    # Transparent Window Blur
    blur:enabled = true
    blur:new_optimizations = true
    blur:size = 2
    blur:passes = 3
    blur:vibrancy = 0.1696
}

general {
    gaps_in = 15
    gaps_out = 30
}


# Move focus with mainMod + arrow keys
bind = $mainMod, left,  movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up,    movefocus, u
bind = $mainMod, down,  movefocus, d

# Move windows with mainMod + shift + arrow keys
bind = $mainMod+shift,  left,  movewindow, l
bind = $mainMod+shift,  right, movewindow, r
bind = $mainMod+shift,  up,    movewindow, u
bind = $mainMod+shift,  down,  movewindow, d

# Move windows across workspaces
bind = $mainMod+shift,  1, movetoworkspace, 1
bind = $mainMod+shift,  2, movetoworkspace, 2
bind = $mainMod+shift,  3, movetoworkspace, 3
bind = $mainMod+shift,  4, movetoworkspace, 4
bind = $mainMod+shift,  5, movetoworkspace, 5
bind = $mainMod+shift,  6, movetoworkspace, 6
bind = $mainMod+shift,  7, movetoworkspace, 7
bind = $mainMod+shift,  8, movetoworkspace, 8
bind = $mainMod+shift,  9, movetoworkspace, 9

